mesh:
  revolve_axis: 2
  revolve_angle: 90
  revolve_layers: 14
  mesh_size: 0.32
  mesh_dimension: 2
  output_format: inp
  ogrid_core_ratio: 0.12
  core_inner_ratio: 0.55
  core_radial_layers: 3
  radial_mapping_beta: 1.0
analysis:
  febio_path: C:/Program Files/FEBioStudio/bin/febio4.exe
  template_feb: template2.feb
  material_name: Proto2_Trial_005
  total_stroke: 1.0
  time_steps: 10
  num_threads: null
  contact_penalty: 5
