materials:
  Ogden_Rubber_v1:
    type: uncoupled viscoelastic
    parameters:
      density: 1.0
      k: 200.0
      pressure_model: Abaqus
      visco:
        t:
        - 0.1
        - 1.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        g:
        - 0.85
        - 0.1
        - 0.05
        - 0.0
        - 0.0
        - 0.0
      elastic:
        type: Ogden
        c:
        - 4.4
        - 0.1
        - 0.01
        - 0.0
        - 0.0
        - 0.0
        m:
        - 0.8
        - 0.1
        - 0.01
        - 0.01
        - 0.01
        - 0.01
  Ogden_Rubber_v2:
    type: uncoupled viscoelastic
    parameters:
      density: 1.0
      k: 300.0
      pressure_model: Abaqus
      visco:
        t:
        - 0.2
        - 1.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        g:
        - 0.85
        - 0.1
        - 0.05
        - 0.0
        - 0.0
        - 0.0
      elastic:
        type: Ogden
        c:
        - 8.8
        - 0.2
        - 0.02
        - 0.0
        - 0.0
        - 0.0
        m:
        - 0.8
        - 0.1
        - 0.01
        - 0.01
        - 0.01
        - 0.01
  Ogden_Rubber_v3:
    type: uncoupled viscoelastic
    parameters:
      density: 1.1
      k: 200.0
      pressure_model: Abaqus
      visco:
        t:
        - 0.1
        - 1.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        g:
        - 0.9
        - 0.05
        - 0.01
        - 0.0
        - 0.0
        - 0.0
      elastic:
        type: Ogden
        c:
        - 2.2
        - 0.05
        - 0.005
        - 0.0
        - 0.0
        - 0.0
        m:
        - 1.2
        - 0.2
        - 0.02
        - 0.02
        - 0.02
        - 0.02
  Ogden_Rubber_v4:
    type: uncoupled viscoelastic
    parameters:
      density: 1.0
      k: 500.0
      pressure_model: Abaqus
      visco:
        t:
        - 0.1
        - 1.0
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        g:
        - 0.5
        - 0.1
        - 0.05
        - 0.0
        - 0.0
        - 0.0
      elastic:
        type: Ogden
        c:
        - 10.0
        - 1.0
        - 0.1
        - 0.0
        - 0.0
        - 0.0
        m:
        - 2.0
        - 0.5
        - 0.05
        - 0.05
        - 0.05
        - 0.05
  Proto2_Trial_002:
    type: uncoupled viscoelastic
    parameters:
      density: 1.0
      k: 200.0
      pressure_model: Abaqus
      visco:
        t:
        - 0.08396342119524303
        - 0.9472839810604432
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        g:
        - 1.140879480620874
        - 0.06396085385900319
        - 0.0508540663048167
        - 0.0
        - 0.0
        - 0.0
      elastic:
        type: Ogden
        c:
        - 2.7200358268534917
        - 0.06200854118241207
        - 0.007650906915514453
        - 0.0
        - 0.0
        - 0.0
        m:
        - 0.8237661743669484
        - 0.09183340223705391
        - 0.007494749682376503
        - 0.011342234736668554
        - 0.005673926327824502
        - 0.0075057357824226175
  Proto2_Trial_003:
    type: uncoupled viscoelastic
    parameters:
      density: 1.0
      k: 200.0
      pressure_model: Abaqus
      visco:
        t:
        - 0.051720653680766074
        - 1.2210796318145885
        - 0.0
        - 0.0
        - 0.0
        - 0.0
        g:
        - 0.7889555436143934
        - 0.054644588181373466
        - 0.04971061460667622
        - 0.0
        - 0.0
        - 0.0
      elastic:
        type: Ogden
        c:
        - 4.887948923591585
        - 0.045574049526399735
        - 0.01129053822281726
        - 0.0
        - 0.0
        - 0.0
        m:
        - 0.48370315873979997
        - 0.04780619115823355
        - 0.01538662644704
        - 0.015587584396894713
        - 0.013700768177397534
        - 0.0076553652300804485
